### ISSUE TITLE
Move card designer text to flavor text field

### ISSUE THREAD

**Issue by brine** [Alsciende/thronesdb-json-data#206] opened 2017-11-06 14:45 UTC
Thoughts on moving the card designer text into the flavor text field?  Considering it doesnt have any impact on a card’s ability or playability, it doesn’t make a lot of sense to have it incuded when an API call requests a card’s rules text.

I can make a pull request for the changes if all are agreed on this.

**Comment by Alsciende** [comment] 2017-11-06 16:17
I agree.

@mplain ? @ystros ?

**Comment by ystros** [comment] 2017-11-06 17:38
From a data integrity perspective, I would suggest moving it to a new optional field like `designer` or `design_info` (similar to the way there's an `illustrator` field) rather than lump it in with the existing `flavor` field. 
The flavor field is more about the quotes that sometimes appear on the card. Having a separate field for designer should also make styling easier on ThronesDB itself, and allowing search-by-designer in the future (though it seems unlikely that'll ever be needed).

That said, if you ultimately want move it into flavor that's fine, just feels strange to me. It won't affect Throneteki either way as we don't use the flavor field.

**Comment by mplain** [comment] 2017-11-06 18:22
I don't think flavor text field is a good fit for that. The way it is now is close to how the card is printed. A dedicated designer field would be fine, just not sure if it's worth the trouble. Either way, I don't have any strong opinion on this.

**Comment by brine** [comment] 2017-11-06 19:17
I suggested flavor text mainly because 1) it would require no backend changes to how card data is displayed on thronesdb, as flavor text already has its own location in the card summary pages, and 2) cards with card designer attribution don't (AFAIK) have flavor text to begin with.

I agree that a dedicated field would be more appropriate, I just don't know enough about the structure of the code to implement a new field to do it on my own.

**Comment by brine** [comment] 2017-11-06 19:18
barring the addition of a new field though, I still believe flavor text is more appropriate than card rules text though.  I personally consider flavor text to be "anything that doesn't impact the functionality of the card"

**Comment by mplain** [comment] 2017-11-06 19:21
That text is in recognition of the designer's feats and merit. To this effect, it's written in bold, so that everyone looking at the card would see every time that this card was designed by that great player. This is how it is intended to work on paper (carton), and I don't see why we should change that for digital implementation.

**Comment by brine** [comment] 2017-11-06 20:59
I understand the importance of it, it doesn't matter to me where it goes as long as its not in the rules text.

**Comment by Alsciende** [comment] 2017-11-13 19:44
Thank you all. Hopefully everyone's happy with the new situation.

**Closed by Alsciende** 2017-11-13 19:44 UTC
